# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFfRe3ZOH0_2j3DeoXVF96lQBC0vjPoq
"""

import pandas as pd
baza={
    "FISH":[  "Aliyeva Ra'no", "Aliyev Ali"   ],
    "Yoshi":["11" ,'10'      ],
    "Jinsi":[ "qiz bola" ,"o'g'il bola"     ],
    "Qaysi maktabda o'qishi":[  "2-maktab" ,"Prezident maktabi"     ],
    "Manzili":[  "Marg'ilon shaxar", "Farg'ona shaxar"        ]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="qiz bola"]
print(filtr)

filtr=db[(db['Jinsi']=="qiz bola")&(db["Yoshi"]>'15')]
print(filtr)